### ISSUE TITLE
Enabled iGPU breaks down dGPU tuning

### ISSUE THREAD

**Issue by 1usmus** [GPUOpen-LibrariesAndSDKs/ADLX#10]
**System:** 
AMD Ryzen 9 7950X + AMD RX 7900 XTX

**Decided to check out the example you provided :**
mainManualGraphicsTuning.cpp 

**Result:**
Destroy ADLX res: 11
This GPU doesn't supported manual graphics tuning

If you turn off the iGPU everything will work.

**Comment by ericjunwei** [comment]
ADLX sample will only pick the first GPU to try on graphics tuning and, on your system, the first one is iGPU, that's why you encounter this problem. You can change the sample code to work on a different GPU. https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/blob/42372fceda024cebff05dcd714e204c35432377b/Samples/CPP/GPUTuning/ManualGraphicsTuning/mainManualGraphicsTuning.cpp#L70C7-L70C7
